apiVersion: webhookconfig.keptn.sh/v1alpha1
kind: WebhookConfig
metadata:
  name: webhook-configuration
spec:
  webhooks:
    - type: sh.keptn.event.je-test.triggered
      requests:
        - >-
          curl --header 'Accept: application/vnd.pagerduty+json;version=2' --header 'Authorization: Token token=y_NbAkKc66ryYTWUXYEu' --header 'Content-Type: application/json' --request GET https://api.pagerduty.com/incidents
      subscriptionID: 04b4ed68-d015-4fb1-a810-af3e1082b31f
      sendFinished: true
      sendStarted: true
