apiVersion: webhookconfig.keptn.sh/v1alpha1
kind: WebhookConfig
metadata:
  name: webhook-configuration
spec:
  webhooks:
    - type: sh.keptn.event.je-test.started
      requests:
        - >-
          curl --header 'Accept: application/vnd.pagerduty+json;version=2' --header 'Authorization: Token={{.env.secret_pagerduty_Token}}' --header 'Content-Type: application/json' --request POST --data '{"incident":{"type":"incident","title":"The test is on triggered event.","service":{"id":"PWIXJZS","type":"service_reference"},"priority":{"id":"P53ZZH5","type":"priority_reference"},"urgency":"high","incident_key":"baf7cf21b1da41b4b0221008339ff357","body":{"type":"incident_body","details":"A disk is getting full on this machine. You should investigate what is causing the disk to fill, and ensure that there is an automated process in place for ensuring data is rotated (eg. logs should have logrotate around them). If data is expected to stay on this disk forever, you should start planning to scale up to a larger disk."},"escalation_policy":{"id":"PT20YPA","type":"escalation_policy_reference"}}}' https://api.pagerduty.com/incidents
      envFrom:
        - name: secret_pagerduty_Token
          secretRef:
            name: pagerduty
            key: Token
      subscriptionID: 04b4ed68-d015-4fb1-a810-af3e1082b31f
      sendFinished: false
      sendStarted: false
