apiVersion: webhookconfig.keptn.sh/v1alpha1
kind: WebhookConfig
metadata:
  name: webhook-configuration
spec:
  webhooks:
    - type: sh.keptn.event.je-test.triggered
      requests:
        - >-
          curl --request POST --data '{"status":"success","message":"Event processed","incident_key":"srv01/HTTP"}' https://events.pagerduty.com/generic/2010-04-15/create_event.json
      subscriptionID: 04b4ed68-d015-4fb1-a810-af3e1082b31f
      sendFinished: true
      sendStarted: true
